# 머신러닝을 시작하기 전 기본 라이브러리
- Numpy
- Scipy
- Scikit-learn
- Pandas
- matplotlib

## Numpy/Pandas 소개
- C로 작성되어 있어 처리속도가 빠른편
- Numpy는 과학 계산을 위한 라이브러리로 다차원 배열을 처리하는데 필요한 여러 기능을 제공한다.  

### numpy 배열
numpy에서 배열은 동일한 타입의 값들을 갖는다.  
배열의 차원을 rank라고 한다.  

shape : 각차원의 크기를 튜플로 표시한 것  
  예> 2행, 3열인 2차원 배열은 rank는 2이고, shape(2,3)  
  
**numpy 배열의 생성**  
1. 파이썬의 리스트를 사용하는 방법  
array()메소드의 인자로 리스트를 넣어 생성한다.  
예> numpy.array([1,2,3])  
1. numpy에서 제공하는 함수를 사용하는 방법  
 - zeros()함수는 배열에 모두 -을 집어넣고,  
 - ones()함수는 모두 1을 집어 넣는다.  
 - full()함수는 사용자가 지정한 값을 넣는데 사용,  
 - eye()함수는 대각선으로는 1이고 나머지는 0 (identity)
1. range(n) : 0 ~ n-1까지의 숫자를 생성하는 함수
1. reshape() : 다차원으로 변형하는 함수

In [1]:
import numpy as np

list1 = [1,2,3,4]
a = np.array(list1)
a

array([1, 2, 3, 4])

In [2]:
a.shape

(4,)

In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b.shape

(2, 3)

In [5]:
# 슬라이싱 가능
print(b[0,0])
print(b[:,1:3])

1
[[2 3]
 [5 6]]


In [6]:
aa = np.zeros([5,2])
aa

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [7]:
type(aa)

numpy.ndarray

In [8]:
aa = np.ones([3,3])
aa

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
aa = np.full([2,3],29)
aa

array([[29, 29, 29],
       [29, 29, 29]])

In [10]:
aa = np.eye(6) #sqare matrix만 먹는듯
aa

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [11]:
# 배열을 꽉채우기
aa = np.array(range(20))
aa

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
#배열 모양 바꾸기
aa.reshape([4,5])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])