짝이 맞지않는 두개의 개체를 더했을때 어케 변할까?  
**색인**이 다른 객체를 더하는 산술연산

In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

s1 = Series([5,6,-1,2],index=['a','c','d','e'])
s2 = Series([3,4,-1,2,7],index = ['a','c','e','f','g'])
print(s1,end='\n\n')
print(s2,end='\n\n')
print(s1+s2)


a    5
c    6
d   -1
e    2
dtype: int64

a    3
c    4
e   -1
f    2
g    7
dtype: int64

a     8.0
c    10.0
d     NaN
e     1.0
f     NaN
g     NaN
dtype: float64


<a color='blue'>있는 인덱스 끼리만 더해짐</a><br>
하나라도 없는 놈들은 NaN

---


In [2]:
list('bdc')

['b', 'd', 'c']

In [3]:
df1 = DataFrame(np.arange(9).reshape(3,3), columns =list('bcd'),\
                index = ['seoul','busan','kwangju'])
df2 = DataFrame(np.arange(12).reshape(4,3), columns =list('bde'),\
                index = ['incheon','seoul','busan','suwon'])

print(df1,end='\n\n')
print(df2,end='\n\n')
print(df1+df2)

         b  c  d
seoul    0  1  2
busan    3  4  5
kwangju  6  7  8

         b   d   e
incheon  0   1   2
seoul    3   4   5
busan    6   7   8
suwon    9  10  11

           b   c     d   e
busan    9.0 NaN  12.0 NaN
incheon  NaN NaN   NaN NaN
kwangju  NaN NaN   NaN NaN
seoul    3.0 NaN   6.0 NaN
suwon    NaN NaN   NaN NaN


index 와 column 모두 같아야 더해짐

---

In [4]:
df3 = DataFrame(np.arange(12).reshape(3,4),columns=list('abcd'))
df4 = DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))
print(df3,end='\n\n')
print(df4,end='\n\n')
print(df3+df4)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN


In [5]:
#옵션을 활용하여 NaN을 0으로 바꾸기
df3.add(df4,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

없는 놈이 있으면 그놈을 0으로 가정하고 계산해줌

---

In [6]:
print(df3.reindex(index = df4.index,columns=df4.columns),end='\n\n')
print(df3.reindex(index = df4.index,columns=df4.columns,fill_value=0),end='\n\n')

     a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN
3  NaN  NaN   NaN   NaN NaN

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0
3  0  0   0   0  0



### DataFrame과 Series의 연산

In [7]:
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr-arr[0]) #브로드 캐스팅

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


In [8]:
df = DataFrame(np.arange(12).reshape(4,3),columns=list('bde'),\
              index = ['seoul','kwangju','daegue','incheon'])
print(df,end='\n\n')

s1 = df.iloc[0]
print(s1,end='\n\n')

print(df-s1,end='\n\n')

s2 = Series(range(3),index=list('bef'))
print('=============')
print(s2,end='\n\n')
print(df+s2)
s3 = df['d']
print('=============',end='\n\n')
print('''
열로 데이터 받아와도 Series로 변환후 연산하면 이렇게됨
''')
print(s3,end='\n\n')
print(df-s3,end='\n\n')

print('=============',end='\n\n')
print('''
열끼리 연산할 경우에는 abb/sub메소드에 axis옵션줘서 사용
''')
print(df.add(s3,axis=0))

         b   d   e
seoul    0   1   2
kwangju  3   4   5
daegue   6   7   8
incheon  9  10  11

b    0
d    1
e    2
Name: seoul, dtype: int32

         b  d  e
seoul    0  0  0
kwangju  3  3  3
daegue   6  6  6
incheon  9  9  9

b    0
e    1
f    2
dtype: int64

           b   d     e   f
seoul    0.0 NaN   3.0 NaN
kwangju  3.0 NaN   6.0 NaN
daegue   6.0 NaN   9.0 NaN
incheon  9.0 NaN  12.0 NaN


열로 데이터 받아와도 Series로 변환후 연산하면 이렇게됨

seoul       1
kwangju     4
daegue      7
incheon    10
Name: d, dtype: int32

          b   d  daegue   e  incheon  kwangju  seoul
seoul   NaN NaN     NaN NaN      NaN      NaN    NaN
kwangju NaN NaN     NaN NaN      NaN      NaN    NaN
daegue  NaN NaN     NaN NaN      NaN      NaN    NaN
incheon NaN NaN     NaN NaN      NaN      NaN    NaN



열끼리 연산할 경우에는 abb/sub메소드에 axis옵션줘서 사용

          b   d   e
seoul     1   2   3
kwangju   7   8   9
daegue   13  14  15
incheon  19  20  21


---

### 함수 적용과 매핑

In [9]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

#np.random모듈에 있는 randn함수는 임의의 정규분포 데이터를 생성한다.
df = DataFrame(np.random.randn(4,3),columns=list('cde'),\
              index = ['seoul','busan','daegu','incheon'])
print(df)

                c         d         e
seoul   -0.154484 -2.374121 -0.805533
busan    0.874166  0.473392  0.427622
daegu    0.593609 -1.674900  2.668389
incheon  0.082363  0.061635 -1.007444


In [10]:
np.abs(df)

c         d         e
seoul    0.154484  2.374121  0.805533
busan    0.874166  0.473392  0.427622
daegu    0.593609  1.674900  2.668389
incheon  0.082363  0.061635  1.007444

numpy에 사용하는 메소드도 사용할수 있음

---

In [11]:
#apply 메소드 사용하기
f = lambda x:x.max()-x.min()

print(df.abs().apply(f))

c    0.791802
d    2.312486
e    2.240767
dtype: float64


In [12]:
#행 기준으로
print(df.apply(f,axis=1))

seoul      2.219637
busan      0.446544
daegu      4.343289
incheon    1.089807
dtype: float64


In [13]:
a = Series(np.random.randn(10000))
a.hist()

---

## 함수 매핑

In [14]:
import pandas as pd
import numpy as np

def f(x):
    return pd.Series([x.min(),x.max()], index = ['min','max'])

df = pd.DataFrame(np.random.randn(4,3),columns=list('cde'),\
              index = ['seoul','busan','daegu','incheon'])

print(df,end='\n=========================\n')
print(df.apply(f),end='\n=========================\n')
print(df.apply(f,axis=1))
print('''
apply 메소드를 이용하여 함수를 적용할수 있음''')

                c         d         e
seoul    0.273675 -1.251516  0.491394
busan   -0.042478  0.273424 -0.845289
daegu   -1.486657 -0.800750 -0.574081
incheon -1.632847 -0.309249  0.889522
            c         d         e
min -1.632847 -1.251516 -0.845289
max  0.273675  0.273424  0.889522
              min       max
seoul   -1.251516  0.491394
busan   -0.845289  0.273424
daegu   -1.486657 -0.574081
incheon -1.632847  0.889522

apply 메소드를 이용하여 함수를 적용할수 있음


In [15]:
# 데이터 프레임 객체에서 실수 값을 문자열 포맷으로 변환할 경우
# applymap 함수 사용
print('.applymap은 각 인자별로 적용되는 듯')
form = lambda x: '%.2f'%x

df.applymap(form)

.applymap은 각 인자별로 적용되는 듯


c      d      e
seoul     0.27  -1.25   0.49
busan    -0.04   0.27  -0.85
daegu    -1.49  -0.80  -0.57
incheon  -1.63  -0.31   0.89

In [16]:
print('Series 객체의 경우 .map() 이용')
df['e'].map(form)

Series 객체의 경우 .map() 이용


seoul       0.49
busan      -0.85
daegu      -0.57
incheon     0.89
Name: e, dtype: object

---

## 정렬과 순위  
- 행의 색인이나 열의 색인 순으로 정렬하는 등의 기준이 필요

In [17]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

df = DataFrame(np.random.randn(4,3), columns = list('bde'),\
              index = ['seoul','busan','daegu','incheon'])

form = lambda x:'%.2f'%x

s1 = df['e'].map(form)
print('index 순으로 정렬할시 .sort_index()')
print(s1.sort_index(),end='\n=========\n')
print('value 순으로 정렬할시 .sort_values()')
print(s1.sort_values(),end='\n=========\n')


index 순으로 정렬할시 .sort_index()
busan      0.44
daegu      1.54
incheon    0.53
seoul      0.90
Name: e, dtype: object
value 순으로 정렬할시 .sort_values()
busan      0.44
incheon    0.53
seoul      0.90
daegu      1.54
Name: e, dtype: object


In [18]:
df2 = DataFrame(np.arange(8).reshape(2,4), index=['three','one'],columns=['d','a','b','c'])
print(df2,end='\n==============\n')
print('.sort_index')
print(df2.sort_index(),end='\n==============\n')
print('.sort_index axis 옵션추가 => 컬럼이름 기준')
print(df2.sort_index(axis=1),end='\n==============\n')
print('.sort_value("d")')
print(df2.sort_values('d'),end='\n==============\n')
print('.sort_value("d",acsending=False)')
print(df2.sort_values('d',ascending=False),end='\n==============\n')

       d  a  b  c
three  0  1  2  3
one    4  5  6  7
.sort_index
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
.sort_index axis 옵션추가 => 컬럼이름 기준
       a  b  c  d
three  1  2  3  0
one    5  6  7  4
.sort_value("d")
       d  a  b  c
three  0  1  2  3
one    4  5  6  7
.sort_value("d",acsending=False)
       d  a  b  c
one    4  5  6  7
three  0  1  2  3


데이터(색인,값)는 기본적으로 오름차순으로 정렬이 된다.  
ascending 옵션으로 내림차순으로 변경가능

---

In [19]:
obj1 = Series([4,np.nan,8,np.nan,-10,2])
print(obj1)
print('\n===========\n')
print('Nan 값이 포함되어있을때 정렬하면??')
print('.sort_values()')
print(obj1.sort_values())

0     4.0
1     NaN
2     8.0
3     NaN
4   -10.0
5     2.0
dtype: float64


Nan 값이 포함되어있을때 정렬하면??
.sort_values()
4   -10.0
5     2.0
0     4.0
2     8.0
1     NaN
3     NaN
dtype: float64


Nan 값은 가장 마지막으로 나온다 (ascending 옵션 상관없이)