짝이 맞지않는 두개의 개체를 더했을때 어케 변할까?  
**색인**이 다른 객체를 더하는 산술연산

In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

s1 = Series([5,6,-1,2],index=['a','c','d','e'])
s2 = Series([3,4,-1,2,7],index = ['a','c','e','f','g'])
print(s1,end='\n\n')
print(s2,end='\n\n')
print(s1+s2)


a    5
c    6
d   -1
e    2
dtype: int64

a    3
c    4
e   -1
f    2
g    7
dtype: int64

a     8.0
c    10.0
d     NaN
e     1.0
f     NaN
g     NaN
dtype: float64


<a color='blue'>있는 인덱스 끼리만 더해짐</a><br>
하나라도 없는 놈들은 NaN

---


In [2]:
list('bdc')

['b', 'd', 'c']

In [3]:
df1 = DataFrame(np.arange(9).reshape(3,3), columns =list('bcd'),\
                index = ['seoul','busan','kwangju'])
df2 = DataFrame(np.arange(12).reshape(4,3), columns =list('bde'),\
                index = ['incheon','seoul','busan','suwon'])

print(df1,end='\n\n')
print(df2,end='\n\n')
print(df1+df2)

         b  c  d
seoul    0  1  2
busan    3  4  5
kwangju  6  7  8

         b   d   e
incheon  0   1   2
seoul    3   4   5
busan    6   7   8
suwon    9  10  11

           b   c     d   e
busan    9.0 NaN  12.0 NaN
incheon  NaN NaN   NaN NaN
kwangju  NaN NaN   NaN NaN
seoul    3.0 NaN   6.0 NaN
suwon    NaN NaN   NaN NaN


index 와 column 모두 같아야 더해짐

---

In [4]:
df3 = DataFrame(np.arange(12).reshape(3,4),columns=list('abcd'))
df4 = DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))
print(df3,end='\n\n')
print(df4,end='\n\n')
print(df3+df4)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN


In [5]:
#옵션을 활용하여 NaN을 0으로 바꾸기
df3.add(df4,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

없는 놈이 있으면 그놈을 0으로 가정하고 계산해줌

---

In [6]:
print(df3.reindex(index = df4.index,columns=df4.columns),end='\n\n')
print(df3.reindex(index = df4.index,columns=df4.columns,fill_value=0),end='\n\n')

     a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN
3  NaN  NaN   NaN   NaN NaN

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0
3  0  0   0   0  0



### DataFrame과 Series의 연산

In [7]:
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr-arr[0]) #브로드 캐스팅

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


In [8]:
df = DataFrame(np.arange(12).reshape(4,3),columns=list('bde'),\
              index = ['seoul','kwangju','daegue','incheon'])
print(df,end='\n\n')

s1 = df.iloc[0]
print(s1,end='\n\n')

print(df-s1,end='\n\n')

s2 = Series(range(3),index=list('bef'))
print('=============')
print(s2,end='\n\n')
print(df+s2)
s3 = df['d']
print('=============',end='\n\n')
print('''
열로 데이터 받아와도 Series로 변환후 연산하면 이렇게됨
''')
print(s3,end='\n\n')
print(df-s3,end='\n\n')

print('=============',end='\n\n')
print('''
열끼리 연산할 경우에는 abb/sub메소드에 axis옵션줘서 사용
''')
print(df.add(s3,axis=0))

         b   d   e
seoul    0   1   2
kwangju  3   4   5
daegue   6   7   8
incheon  9  10  11

b    0
d    1
e    2
Name: seoul, dtype: int32

         b  d  e
seoul    0  0  0
kwangju  3  3  3
daegue   6  6  6
incheon  9  9  9

b    0
e    1
f    2
dtype: int64

           b   d     e   f
seoul    0.0 NaN   3.0 NaN
kwangju  3.0 NaN   6.0 NaN
daegue   6.0 NaN   9.0 NaN
incheon  9.0 NaN  12.0 NaN


열로 데이터 받아와도 Series로 변환후 연산하면 이렇게됨

seoul       1
kwangju     4
daegue      7
incheon    10
Name: d, dtype: int32

          b   d  daegue   e  incheon  kwangju  seoul
seoul   NaN NaN     NaN NaN      NaN      NaN    NaN
kwangju NaN NaN     NaN NaN      NaN      NaN    NaN
daegue  NaN NaN     NaN NaN      NaN      NaN    NaN
incheon NaN NaN     NaN NaN      NaN      NaN    NaN



열끼리 연산할 경우에는 abb/sub메소드에 axis옵션줘서 사용

          b   d   e
seoul     1   2   3
kwangju   7   8   9
daegue   13  14  15
incheon  19  20  21


---

### 함수 적용과 매핑

In [9]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

#np.random모듈에 있는 randn함수는 임의의 정규분포 데이터를 생성한다.
df = DataFrame(np.random.randn(4,3),columns=list('cde'),\
              index = ['seoul','busan','daegu','incheon'])
print(df)

                c         d         e
seoul   -0.291002  1.327633 -0.239090
busan    0.849864 -2.376598 -0.865298
daegu    0.463062  0.583263 -0.536423
incheon -0.058834 -1.015811  0.288424


In [10]:
np.abs(df)

c         d         e
seoul    0.291002  1.327633  0.239090
busan    0.849864  2.376598  0.865298
daegu    0.463062  0.583263  0.536423
incheon  0.058834  1.015811  0.288424

numpy에 사용하는 메소드도 사용할수 있음

---

In [11]:
#apply 메소드 사용하기
f = lambda x:x.max()-x.min()

print(df.abs().apply(f))

c    0.791029
d    1.793335
e    0.626207
dtype: float64


In [12]:
#행 기준으로
print(df.apply(f,axis=1))

seoul      1.618635
busan      3.226461
daegu      1.119686
incheon    1.304235
dtype: float64


In [13]:
a = Series(np.random.randn(10000))
a.hist()

---

## 함수 매핑

In [14]:
import pandas as pd
import numpy as np

def f(x):
    return pd.Series([x.min(),x.max()], index = ['min','max'])

df = pd.DataFrame(np.random.randn(4,3),columns=list('cde'),\
              index = ['seoul','busan','daegu','incheon'])

print(df,end='\n=========================\n')
print(df.apply(f),end='\n=========================\n')
print(df.apply(f,axis=1))
print('''
apply 메소드를 이용하여 함수를 적용할수 있음''')

                c         d         e
seoul   -0.331136  0.739222  0.082745
busan    1.849158 -0.360785 -0.246701
daegu   -0.407137  0.343590  0.486034
incheon  0.719524  0.085979  0.058649
            c         d         e
min -0.407137 -0.360785 -0.246701
max  1.849158  0.739222  0.486034
              min       max
seoul   -0.331136  0.739222
busan   -0.360785  1.849158
daegu   -0.407137  0.486034
incheon  0.058649  0.719524

apply 메소드를 이용하여 함수를 적용할수 있음


In [15]:
# 데이터 프레임 객체에서 실수 값을 문자열 포맷으로 변환할 경우
# applymap 함수 사용
print('.applymap은 각 인자별로 적용되는 듯')
form = lambda x: '%.2f'%x

df.applymap(form)

.applymap은 각 인자별로 적용되는 듯


c      d      e
seoul    -0.33   0.74   0.08
busan     1.85  -0.36  -0.25
daegu    -0.41   0.34   0.49
incheon   0.72   0.09   0.06

In [16]:
print('Series 객체의 경우 .map() 이용')
df['e'].map(form)

Series 객체의 경우 .map() 이용


seoul       0.08
busan      -0.25
daegu       0.49
incheon     0.06
Name: e, dtype: object

---

## 정렬과 순위  
- 행의 색인이나 열의 색인 순으로 정렬하는 등의 기준이 필요

In [17]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

df = DataFrame(np.random.randn(4,3), columns = list('bde'),\
              index = ['seoul','busan','daegu','incheon'])

form = lambda x:'%.2f'%x

s1 = df['e'].map(form)
print('index 순으로 정렬할시 .sort_index()')
print(s1.sort_index(),end='\n=========\n')
print('value 순으로 정렬할시 .sort_values()')
print(s1.sort_values(),end='\n=========\n')


index 순으로 정렬할시 .sort_index()
busan      -1.16
daegu      -0.49
incheon    -0.95
seoul      -0.19
Name: e, dtype: object
value 순으로 정렬할시 .sort_values()
seoul      -0.19
daegu      -0.49
incheon    -0.95
busan      -1.16
Name: e, dtype: object


In [18]:
df2 = DataFrame(np.arange(8).reshape(2,4), index=['three','one'],columns=['d','a','b','c'])
print(df2,end='\n==============\n')
print('.sort_index')
print(df2.sort_index(),end='\n==============\n')
print('.sort_index axis 옵션추가 => 컬럼이름 기준')
print(df2.sort_index(axis=1),end='\n==============\n')
print('.sort_value("d")')
print(df2.sort_values('d'),end='\n==============\n')
print('.sort_value("d",acsending=False)')
print(df2.sort_values('d',ascending=False),end='\n==============\n')

       d  a  b  c
three  0  1  2  3
one    4  5  6  7
.sort_index
       d  a  b  c
one    4  5  6  7
three  0  1  2  3
.sort_index axis 옵션추가 => 컬럼이름 기준
       a  b  c  d
three  1  2  3  0
one    5  6  7  4
.sort_value("d")
       d  a  b  c
three  0  1  2  3
one    4  5  6  7
.sort_value("d",acsending=False)
       d  a  b  c
one    4  5  6  7
three  0  1  2  3


데이터(색인,값)는 기본적으로 오름차순으로 정렬이 된다.  
ascending 옵션으로 내림차순으로 변경가능

---

In [19]:
obj1 = Series([4,np.nan,8,np.nan,-10,2])
print(obj1)
print('\n===========\n')
print('Nan 값이 포함되어있을때 정렬하면??')
print('.sort_values()')
print(obj1.sort_values())

0     4.0
1     NaN
2     8.0
3     NaN
4   -10.0
5     2.0
dtype: float64


Nan 값이 포함되어있을때 정렬하면??
.sort_values()
4   -10.0
5     2.0
0     4.0
2     8.0
1     NaN
3     NaN
dtype: float64


Nan 값은 가장 마지막으로 나온다 (ascending 옵션 상관없이)

In [20]:
frame = DataFrame({
    'b':[4,7,-5,2],
    'a':[0,1,0,1],
})
print(frame,end='\n===========\n')
print("frame.sort_values(by='b')")
print(frame.sort_values(by='b'),end='\n===========\n')

   b  a
0  4  0
1  7  1
2 -5  0
3  2  1
frame.sort_values(by='b')
   b  a
2 -5  0
3  2  1
0  4  0
1  7  1


여러개의 컬럼을 기준으로 정렬하고 싶다면 리스트 형태로 주면됨

In [21]:
print("frame.sort_values(by='a')")
print(frame.sort_values(by='a'),end='\n===========\n')
print("frame.sort_values(by=['a','b'])")
print(frame.sort_values(by=['a','b']),end='\n===========\n')

frame.sort_values(by='a')
   b  a
0  4  0
2 -5  0
1  7  1
3  2  1
frame.sort_values(by=['a','b'])
   b  a
2 -5  0
0  4  0
3  2  1
1  7  1


먼저 정렬하기로 한놈이 우선순위가 높음  

---

**순위 정하는 함수 rank()**

In [22]:
enter = lambda : print('================')
obj3 = Series([7,-2,7,4,2,0,4])
print(obj3,end='\n=========================\n')
a = "obj3.rank()"
print(a,'\n',eval(a))
print('같은 순위가 있을때에는 두개의 평균값으로 나옴 ( 4위 5위가 같은 값일때 -> 4.5)',end='\n=========================\n')
a = "obj3.rank(method='first')"
print(a,'\n',eval(a))
print('같은 값이 있을때에는 데이터의 순서에 따라 순위를 매기겠다.')
enter()
a = "obj3.rank(ascending=False)"
print(a,'\n',eval(a))
print('내림차순 순서에 따라 순위 정하기')
enter()

0    7
1   -2
2    7
3    4
4    2
5    0
6    4
dtype: int64
obj3.rank() 
 0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64
같은 순위가 있을때에는 두개의 평균값으로 나옴 ( 4위 5위가 같은 값일때 -> 4.5)
obj3.rank(method='first') 
 0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64
같은 값이 있을때에는 데이터의 순서에 따라 순위를 매기겠다.
obj3.rank(ascending=False) 
 0    1.5
1    7.0
2    1.5
3    3.5
4    5.0
5    6.0
6    3.5
dtype: float64
내림차순 순서에 따라 순위 정하기


In [23]:
print(obj3.rank(ascending=False,method='max'))
print('그룹지어서 순위 매김.. 같은거중 가장 낮은놈 기준인듯 (자매품 min)')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64
그룹지어서 순위 매김.. 같은거중 가장 낮은놈 기준인듯 (자매품 min)
