짝이 맞지않는 두개의 개체를 더했을때 어케 변할까?  
**색인**이 다른 객체를 더하는 산술연산

In [1]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

s1 = Series([5,6,-1,2],index=['a','c','d','e'])
s2 = Series([3,4,-1,2,7],index = ['a','c','e','f','g'])
print(s1,end='\n\n')
print(s2,end='\n\n')
print(s1+s2)


a    5
c    6
d   -1
e    2
dtype: int64

a    3
c    4
e   -1
f    2
g    7
dtype: int64

a     8.0
c    10.0
d     NaN
e     1.0
f     NaN
g     NaN
dtype: float64


<a color='blue'>있는 인덱스 끼리만 더해짐</a><br>
하나라도 없는 놈들은 NaN

---


In [2]:
list('bdc')

['b', 'd', 'c']

In [3]:
df1 = DataFrame(np.arange(9).reshape(3,3), columns =list('bcd'),\
                index = ['seoul','busan','kwangju'])
df2 = DataFrame(np.arange(12).reshape(4,3), columns =list('bde'),\
                index = ['incheon','seoul','busan','suwon'])

print(df1,end='\n\n')
print(df2,end='\n\n')
print(df1+df2)

         b  c  d
seoul    0  1  2
busan    3  4  5
kwangju  6  7  8

         b   d   e
incheon  0   1   2
seoul    3   4   5
busan    6   7   8
suwon    9  10  11

           b   c     d   e
busan    9.0 NaN  12.0 NaN
incheon  NaN NaN   NaN NaN
kwangju  NaN NaN   NaN NaN
seoul    3.0 NaN   6.0 NaN
suwon    NaN NaN   NaN NaN


index 와 column 모두 같아야 더해짐

---

In [4]:
df3 = DataFrame(np.arange(12).reshape(3,4),columns=list('abcd'))
df4 = DataFrame(np.arange(20).reshape(4,5),columns=list('abcde'))
print(df3,end='\n\n')
print(df4,end='\n\n')
print(df3+df4)

   a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

    a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

      a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN


In [5]:
#옵션을 활용하여 NaN을 0으로 바꾸기
df3.add(df4,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

없는 놈이 있으면 그놈을 0으로 가정하고 계산해줌

---

In [6]:
print(df3.reindex(index = df4.index,columns=df4.columns),end='\n\n')
print(df3.reindex(index = df4.index,columns=df4.columns,fill_value=0),end='\n\n')

     a    b     c     d   e
0  0.0  1.0   2.0   3.0 NaN
1  4.0  5.0   6.0   7.0 NaN
2  8.0  9.0  10.0  11.0 NaN
3  NaN  NaN   NaN   NaN NaN

   a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0
3  0  0   0   0  0



### DataFrame과 Series의 연산

In [7]:
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr-arr[0]) #브로드 캐스팅

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


In [8]:
df = DataFrame(np.arange(12).reshape(4,3),columns=list('bde'),\
              index = ['seoul','kwangju','daegue','incheon'])
print(df,end='\n\n')

s1 = df.iloc[0]
print(s1,end='\n\n')

print(df-s1,end='\n\n')

s2 = Series(range(3),index=list('bef'))
print('=============')
print(s2,end='\n\n')
print(df+s2)
s3 = df['d']
print('=============',end='\n\n')
print('''
열로 데이터 받아와도 Series로 변환후 연산하면 이렇게됨
''')
print(s3,end='\n\n')
print(df-s3,end='\n\n')

print('=============',end='\n\n')
print('''
열끼리 연산할 경우에는 abb/sub메소드에 axis옵션줘서 사용
''')
print(df.add(s3,axis=0))

         b   d   e
seoul    0   1   2
kwangju  3   4   5
daegue   6   7   8
incheon  9  10  11

b    0
d    1
e    2
Name: seoul, dtype: int32

         b  d  e
seoul    0  0  0
kwangju  3  3  3
daegue   6  6  6
incheon  9  9  9

b    0
e    1
f    2
dtype: int64

           b   d     e   f
seoul    0.0 NaN   3.0 NaN
kwangju  3.0 NaN   6.0 NaN
daegue   6.0 NaN   9.0 NaN
incheon  9.0 NaN  12.0 NaN


열로 데이터 받아와도 Series로 변환후 연산하면 이렇게됨

seoul       1
kwangju     4
daegue      7
incheon    10
Name: d, dtype: int32

          b   d  daegue   e  incheon  kwangju  seoul
seoul   NaN NaN     NaN NaN      NaN      NaN    NaN
kwangju NaN NaN     NaN NaN      NaN      NaN    NaN
daegue  NaN NaN     NaN NaN      NaN      NaN    NaN
incheon NaN NaN     NaN NaN      NaN      NaN    NaN



열끼리 연산할 경우에는 abb/sub메소드에 axis옵션줘서 사용

          b   d   e
seoul     1   2   3
kwangju   7   8   9
daegue   13  14  15
incheon  19  20  21


---

### 함수 적용과 매핑

In [9]:
import pandas as pd
from pandas import Series,DataFrame
import numpy as np

#np.random모듈에 있는 randn함수는 임의의 정규분포 데이터를 생성한다.
df = DataFrame(np.random.randn(4,3),columns=list('cde'),\
              index = ['seoul','busan','daegu','incheon'])
print(df)

                c         d         e
seoul   -1.299303  0.073510  0.194438
busan   -2.440173  0.507220  2.183287
daegu    1.376019  1.722053 -1.465485
incheon  1.056334 -0.088646 -0.121921


In [10]:
np.abs(df)

c         d         e
seoul    1.299303  0.073510  0.194438
busan    2.440173  0.507220  2.183287
daegu    1.376019  1.722053  1.465485
incheon  1.056334  0.088646  0.121921

numpy에 사용하는 메소드도 사용할수 있음

---

In [11]:
#apply 메소드 사용하기
f = lambda x:x.max()-x.min()

print(df.abs().apply(f))

c    1.383839
d    1.648543
e    2.061366
dtype: float64


In [12]:
#행 기준으로
print(df.apply(f,axis=1))

seoul      1.493741
busan      4.623460
daegu      3.187537
incheon    1.178256
dtype: float64


In [13]:
a = Series(np.random.randn(10000))
a.hist()